package classes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mélanie
 */


import javax.swing.*;
import javax.swing.table.TableColumn;

public class Table
{
  public static void main(String args[]) 
  {
    JFrame f = new JFrame();
    f.setSize(450, 150);

    //Nom des colonnes
    String[] columns = new String[] {
        "Nom",
        "Prénom", 
        "Compétences", 
        "Projet"
    };

    //données automatiques
    Object[][] data = new Object[][] {
        {"Bida", "Justine", "Dévloppeur web, Inégnieur Son", "Application client A" },
        {"Roye", "Roger", "Inégnieur Son, Développeur Application", "Application client A"  },
        {"Ciopi", "Damien", "Dévloppeur web, Développeur jeu vidéo", "Application client A" },
    };
 
    //on créé une table
    JTable table = new JTable(data, columns);

    //la colonne 3, celle des projets, sera celle où l'on mettra la combobox
    TableColumn col = table.getColumnModel().getColumn(3);
    // créer un ComboBox
    JComboBox<String> cb = new JComboBox<>();
    cb.addItem("Application client A");
    cb.addItem("Développement site web");
    cb.addItem("Jeu client G");
    
    col.setCellEditor(new DefaultCellEditor(cb));

    JScrollPane scroll = new JScrollPane(table);
    table.setFillsViewportHeight(true);
		
    
    f.getContentPane().add(scroll);
    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    f.setVisible(true);
  }
}

public class Table extends javax.swing.JInternalFrame {

    /**
     * Creates new form table
     */
    public Table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
