/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalFrames;

/**
 *
 * @author Mélanie
 */
public class AddProject extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddProject
     */
    public AddProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new org.netbeans.modules.form.InvalidComponent();
        jCalendar2 = new org.netbeans.modules.form.InvalidComponent();
        jDayChooser1 = new org.netbeans.modules.form.InvalidComponent();
        jSpinField1 = new org.netbeans.modules.form.InvalidComponent();
        jDayChooser2 = new org.netbeans.modules.form.InvalidComponent();
        jMonthChooser1 = new org.netbeans.modules.form.InvalidComponent();
        jYearChooser1 = new org.netbeans.modules.form.InvalidComponent();
        jDateChooser2 = new org.netbeans.modules.form.InvalidComponent();
        jCalendar1 = new org.netbeans.modules.form.InvalidComponent();
        jTextField1 = new javax.swing.JTextField();
        jCalendar3 = new org.netbeans.modules.form.InvalidComponent();
        jScrollBar1 = new javax.swing.JScrollBar();
        titre = new javax.swing.JLabel();
        intituleProjet = new javax.swing.JLabel();
        intitule = new javax.swing.JTextField();
        startProject = new org.netbeans.modules.form.InvalidComponent();
        datedebut = new javax.swing.JLabel();
        datefin = new javax.swing.JLabel();
        endProject = new org.netbeans.modules.form.InvalidComponent();
        nbEmploye = new org.netbeans.modules.form.InvalidComponent();
        jLabel2 = new javax.swing.JLabel();
        competence = new javax.swing.JPanel();
        Comp = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        nbemployecomp = new javax.swing.JLabel();
        nbemployecompetence = new org.netbeans.modules.form.InvalidComponent();
        addSkill = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        titre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titre.setForeground(new java.awt.Color(0, 204, 0));
        titre.setText("Ajouter un projet ");

        intituleProjet.setText("Saisir l'intitulé du projet : ");

        datedebut.setText("Date de début du projet : ");

        datefin.setText("Date de fin de projet :");

        jLabel2.setText("Nombre d'employés souhaités pour le projet :");

        competence.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 2, true));

        Comp.setText("Compétence :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concepteur", "Designer", "Développeur" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        nbemployecomp.setText("Nombre d'employés :");

        addSkill.setBackground(new java.awt.Color(0, 204, 0));
        addSkill.setText("Ajouter une autre compétence nécessaire");

        javax.swing.GroupLayout competenceLayout = new javax.swing.GroupLayout(competence);
        competence.setLayout(competenceLayout);
        competenceLayout.setHorizontalGroup(
            competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(competenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Comp)
                .addGap(18, 18, 18)
                .addGroup(competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(competenceLayout.createSequentialGroup()
                        .addComponent(addSkill)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(competenceLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nbemployecomp)
                        .addGap(32, 32, 32)
                        .addComponent(nbemployecompetence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        competenceLayout.setVerticalGroup(
            competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(competenceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nbemployecompetence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Comp)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nbemployecomp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSkill)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intituleProjet)
                        .addGap(18, 18, 18)
                        .addComponent(intitule, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nbEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(datedebut)
                                .addComponent(datefin))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(endProject, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(startProject, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(competence, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intituleProjet)
                    .addComponent(intitule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datedebut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(endProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datefin))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nbEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(competence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Comp;
    private javax.swing.JButton addSkill;
    private javax.swing.JPanel competence;
    private javax.swing.JLabel datedebut;
    private javax.swing.JLabel datefin;
    private org.netbeans.modules.form.InvalidComponent endProject;
    private javax.swing.JTextField intitule;
    private javax.swing.JLabel intituleProjet;
    private org.netbeans.modules.form.InvalidComponent jCalendar1;
    private org.netbeans.modules.form.InvalidComponent jCalendar2;
    private org.netbeans.modules.form.InvalidComponent jCalendar3;
    private javax.swing.JComboBox<String> jComboBox1;
    private org.netbeans.modules.form.InvalidComponent jDateChooser1;
    private org.netbeans.modules.form.InvalidComponent jDateChooser2;
    private org.netbeans.modules.form.InvalidComponent jDayChooser1;
    private org.netbeans.modules.form.InvalidComponent jDayChooser2;
    private javax.swing.JLabel jLabel2;
    private org.netbeans.modules.form.InvalidComponent jMonthChooser1;
    private javax.swing.JScrollBar jScrollBar1;
    private org.netbeans.modules.form.InvalidComponent jSpinField1;
    private javax.swing.JTextField jTextField1;
    private org.netbeans.modules.form.InvalidComponent jYearChooser1;
    private org.netbeans.modules.form.InvalidComponent nbEmploye;
    private javax.swing.JLabel nbemployecomp;
    private org.netbeans.modules.form.InvalidComponent nbemployecompetence;
    private org.netbeans.modules.form.InvalidComponent startProject;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
