/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.internal;

import java.awt.Color;
import model.*;
import controller.*;
/**
 *
 * @author Mélanie
 */
public class AddProject extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddProject
     */
    private CreateProjectModel model;
    
    public AddProject()
    {
        initComponents();
        this.getContentPane().setBackground(new Color(35,35,40));
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        model = new CreateProjectModel(this);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        addHumanNeed.addActionListener(new AddHumanNeedController(this, model));
        removeHumanNeed.addActionListener(new RemoveHumanNeedController(this, model));
    }
    
    public void setNeedsArea(String val)
    {
        humanNeedArea.setText(val);
    }
    
    public void setHumanNeedValue(int val)
    {
        humanNeedNumber.setValue(val);
    }
    
    public String getSkillSelected()
    {
        return skillSelector.getSelectedItem().toString();
    }
    
    public int getHumanNeedNumber()
    {
        return humanNeedNumber.getValue();
    }
    
    public String getProjectName()
    {
        return projectName.getText();
    }
    
    public String getDescription()
    {
        return projectDescription.getText();
    }
    
    public String getStartDate()
    {
        return startDate.getDate().toString();
    }
    
    public String getEndDate()
    {
        return endDate.getDate().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jSpinField1 = new com.toedter.components.JSpinField();
        jDayChooser2 = new com.toedter.calendar.JDayChooser();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jTextField1 = new javax.swing.JTextField();
        jCalendar3 = new com.toedter.calendar.JCalendar();
        jScrollBar1 = new javax.swing.JScrollBar();
        titre = new javax.swing.JLabel();
        intituleProjet = new javax.swing.JLabel();
        projectName = new javax.swing.JTextField();
        startDate = new com.toedter.calendar.JDateChooser();
        datedebut = new javax.swing.JLabel();
        datefin = new javax.swing.JLabel();
        endDate = new com.toedter.calendar.JDateChooser();
        competence = new javax.swing.JPanel();
        Comp = new javax.swing.JLabel();
        skillSelector = new javax.swing.JComboBox<>();
        nbemployecomp = new javax.swing.JLabel();
        humanNeedNumber = new com.toedter.components.JSpinField();
        addHumanNeed = new javax.swing.JButton();
        removeHumanNeed = new javax.swing.JButton();
        createProjectButton = new javax.swing.JButton();
        errorResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectDescription = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        humanNeedsArea = new javax.swing.JScrollPane();
        humanNeedArea = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(35, 35, 40));
        setBorder(new javax.swing.border.MatteBorder(null));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        titre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(255, 255, 255));
        titre.setText("Ajouter un projet ");

        intituleProjet.setForeground(new java.awt.Color(255, 255, 255));
        intituleProjet.setText("Saisir l'intitulé du projet : ");

        startDate.setDateFormatString("d/m/y");

        datedebut.setForeground(new java.awt.Color(255, 255, 255));
        datedebut.setText("Date de début du projet : ");

        datefin.setForeground(new java.awt.Color(255, 255, 255));
        datefin.setText("Date de fin de projet :");

        endDate.setDateFormatString("d/m/y");

        competence.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 2, true));
        competence.setMaximumSize(new java.awt.Dimension(425, 85));
        competence.setPreferredSize(new java.awt.Dimension(425, 85));

        Comp.setText("Compétence :");

        skillSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concepteur", "Designer", "Développeur" }));

        nbemployecomp.setText("Nombre d'employés :");

        humanNeedNumber.setMaximum(100);
        humanNeedNumber.setMinimum(1);
        humanNeedNumber.setValue(1);

        addHumanNeed.setBackground(new java.awt.Color(0, 204, 0));
        addHumanNeed.setText("Ajouter ce besoin");
        addHumanNeed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        removeHumanNeed.setBackground(new java.awt.Color(255, 0, 51));
        removeHumanNeed.setForeground(new java.awt.Color(255, 255, 255));
        removeHumanNeed.setText("Retirer ce besoin");

        javax.swing.GroupLayout competenceLayout = new javax.swing.GroupLayout(competence);
        competence.setLayout(competenceLayout);
        competenceLayout.setHorizontalGroup(
            competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(competenceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, competenceLayout.createSequentialGroup()
                        .addComponent(Comp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(skillSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(removeHumanNeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(competenceLayout.createSequentialGroup()
                        .addComponent(nbemployecomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(humanNeedNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addHumanNeed))
                .addGap(33, 33, 33))
        );
        competenceLayout.setVerticalGroup(
            competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(competenceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(competenceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(humanNeedNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(skillSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nbemployecomp))))
                    .addComponent(Comp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(competenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHumanNeed)
                    .addComponent(removeHumanNeed))
                .addContainerGap())
        );

        createProjectButton.setText("Créer ce projet");
        createProjectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectButtonActionPerformed(evt);
            }
        });

        errorResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        projectDescription.setColumns(20);
        projectDescription.setRows(3);
        projectDescription.setTabSize(6);
        jScrollPane1.setViewportView(projectDescription);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Description :");

        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1731, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        humanNeedArea.setEditable(false);
        humanNeedArea.setColumns(20);
        humanNeedArea.setRows(5);
        humanNeedsArea.setViewportView(humanNeedArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(createProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorResult, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datedebut)
                                    .addComponent(datefin)
                                    .addComponent(intituleProjet)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(projectName)
                                    .addComponent(endDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(startDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(competence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(humanNeedsArea, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1731, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(errorResult))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(intituleProjet)
                            .addComponent(projectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datedebut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datefin))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(humanNeedsArea, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(competence, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(createProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(648, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectButtonActionPerformed
        model.CreateProject();// TODO add your handling code here:
    }//GEN-LAST:event_createProjectButtonActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Comp;
    private javax.swing.JButton addHumanNeed;
    private javax.swing.JPanel competence;
    private javax.swing.JButton createProjectButton;
    private javax.swing.JLabel datedebut;
    private javax.swing.JLabel datefin;
    public com.toedter.calendar.JDateChooser endDate;
    public javax.swing.JLabel errorResult;
    private javax.swing.JTextArea humanNeedArea;
    private com.toedter.components.JSpinField humanNeedNumber;
    private javax.swing.JScrollPane humanNeedsArea;
    private javax.swing.JLabel intituleProjet;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private com.toedter.calendar.JCalendar jCalendar3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private com.toedter.calendar.JDayChooser jDayChooser2;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel nbemployecomp;
    public javax.swing.JTextArea projectDescription;
    public javax.swing.JTextField projectName;
    private javax.swing.JButton removeHumanNeed;
    private javax.swing.JComboBox<String> skillSelector;
    public com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
