/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.internal;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.Set;
import javax.swing.JPanel;
import model.utility.Display;
import model.utility.ServerCommunication;
import model.utility.User;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;
import static view.internal.HomeNavigationButtonsPanel.displayRightWindow;
import view.panel.ApproveUserPanel;

/**
 *
 * @author gaeta
 */
public class ApproveUsers extends javax.swing.JInternalFrame {

    private HomeNavigationButtonsPanel button;
    /**
     * Creates new form ApproveUsers
     * @param button
     */
    public ApproveUsers(HomeNavigationButtonsPanel button) {
        initComponents();
        this.button = button;
        Display.removeBorders(this);
        this.getContentPane().setBackground(new Color(35, 35, 40));
        initialize();
    }
    
    private void initialize() {
        
        ServerCommunication s = new ServerCommunication();

        String res = s.sendGetRequest("getNonApprovedAccount=true");
        
        Object o = JSONValue.parse(res);

        JSONArray jsonArray = (JSONArray) o;         
        
        
        JPanel innerPanel = new JPanel();
        innerPanel.setBorder(null);
        int nbComptes = jsonArray.size();
        if (nbComptes < 4) {
            innerPanel.setLayout(new GridLayout(4, 1, 5, 15));
        } else {
            innerPanel.setLayout(new GridLayout(jsonArray.size(), 1, 5, 15));
        }
        
        innerPanel.setBackground(new Color(35, 35, 40));
        
        //on ajoute ensuite les comptes a approuver
        for(Object object:jsonArray)
        {
            if(object instanceof JSONObject) 
            {
                JSONObject jsonObject = (JSONObject)object;

                Set<String> keys =jsonObject.keySet();
                
                for(String key:keys) 
                {

                   Object newJson = jsonObject.get(key);
                   
                   JSONObject newObj = (JSONObject)newJson;

                   //recuperation des infos
                   String firstname = newObj.get("firstname").toString();
                   String surname = newObj.get("surname").toString();
                   String login = newObj.get("login").toString();
                   String role = newObj.get("role").toString();
                   String admin = newObj.get("admin").toString();
                   String pp = newObj.get("profile_pic").toString();
                   String description = newObj.get("others").toString();
                   
                   User user = new User(login, firstname, surname, admin, role, description, pp, false);
                   
                   ApproveUserPanel userPanel = new ApproveUserPanel(user, this.button);
                   //ajout au jpanel
                   innerPanel.add(userPanel);

                }               
            }
        }
        //ajout du panel dans le scrollPane
        approveScrollPane.setViewportView(innerPanel);

    }
    
    public void update() {
        displayRightWindow(this);
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        approveScrollPane = new javax.swing.JScrollPane();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Approuver les comptes des personnels");

        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(1698, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        approveScrollPane.setBackground(new java.awt.Color(35, 35, 40));
        approveScrollPane.setBorder(null);
        approveScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        approveScrollPane.setPreferredSize(new java.awt.Dimension(1698, 1073));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1308, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(approveScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(approveScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane approveScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
