/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.internal;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import model.utility.Display;
import model.utility.User;

/**
 *
 * @author gaeta
 */
public class ProfileView extends javax.swing.JInternalFrame {

    private User user;
    /**
     * Creates new form ProfileView
     * @param user
     */
    public ProfileView(User user) {
        initComponents();
        Display.removeBorders(this);
        this.user = user;
        stylise();
        initializeElts();
    }

    private void initializeElts(){
        Image image = null;
        try {
            URL url = new URL("https://oplo.000webhostapp.com/resources/profiles/pictures/" + getUser().getProfile_pic());
            image = ImageIO.read(url);
            Image scaled = image.getScaledInstance(200, 200, Image.SCALE_DEFAULT);
            pp.setIcon(new ImageIcon(scaled));
        } 
        catch (IOException e) {

        }
    }
    
    private void stylise() {
        
    }
    
    public User getUser() {
        return this.user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(554, 554, 554)
                .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(789, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pp;
    // End of variables declaration//GEN-END:variables
}
