/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.internal;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import view.*;
import model.utility.Display;
import java.io.File;
import java.util.ArrayList;
import java.util.Set;
import model.UserModel;
import model.utility.ServerCommunication;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;

/**
 *
 * @author gaeta
 */
public class Registration extends javax.swing.JInternalFrame {
    
    private javax.swing.JFrame parentTemp;
       private boolean add;
       private boolean canCommunicateWithServer = true;
       private File myfile;
    /**
     * Creates new form Registration
     * @param parent
     */
    public Registration(javax.swing.JFrame parent)
    {
        Display.removeBorders(this);
        initComponents();
        swapButton.setText("Ajouter");
        ArrayList<String> list_of_skills = this.LoadSkillList();
        swapButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e){
                swapAddVariable();
            }
        });
        approveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e){
                if (add){
                    addSkillToUser();
                    addSkillToField();
                }
                else
                {
                removeSkillFromField();}
            }

            private void removeSkillFromField() {
                chosenSkills.removeItem((String)skillToAddOrRemove.getSelectedItem());
            }

            private void addSkillToField() {
                boolean exists = false;
                for (int index = 0; index < chosenSkills.getItemCount() && !exists; index++) {
                if (skillToAddOrRemove.getSelectedItem().equals(chosenSkills.getItemAt(index))) {
                                exists = true;
                }
            }
            if (!exists && canCommunicateWithServer) {
              chosenSkills.addItem((String)skillToAddOrRemove.getSelectedItem());
            }
                
                
            }
        });
        for(String name:list_of_skills)
        {
            skillToAddOrRemove.addItem(name);
        }
        
        this.getContentPane().setBackground(new Color(35,35,40));
        this.parentTemp = parent;
    }
    
    public File getFile(){
        return this.myfile;
    }
    
    public ArrayList<String> getSkills(){
        
       int n = chosenSkills.getItemCount();
       ArrayList<String> res = new ArrayList<String>();
        for (int i = 0; i < n; i++) {
            res.add(chosenSkills.getItemAt(i));
        }
        return res;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inscription = new javax.swing.JToggleButton();
        infosInscription = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        others = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        profile = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        skillToAddOrRemove = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        approveButton = new javax.swing.JButton();
        swapButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        chosenSkills = new javax.swing.JComboBox<>();
        chosenFileLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 35, 40));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Identifiant*");

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Mot de passe*");

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Prénom*");

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Nom*");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Bio");

        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Inscription");

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("*Champs obligatoires");

        inscription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inscription.setText("M'inscrire");
        inscription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscriptionActionPerformed(evt);
            }
        });

        infosInscription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infosInscription.setForeground(java.awt.Color.white);
        infosInscription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        others.setColumns(20);
        others.setRows(5);
        jScrollPane1.setViewportView(others);

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Photo de profil");

        profile.setSelected(true);
        profile.setText("Parcourir");
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Votre inscription sera soumise à validation auprès de votre responsable");

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Statut dans l'entreprise");

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Employé", "Chef de projet", "Responsable scientifique" }));

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Droits administrateur");
        jLabel11.setToolTipText("");

        admin.add(yes);
        yes.setForeground(java.awt.Color.white);
        yes.setText("Oui");
        yes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        admin.add(no);
        no.setForeground(java.awt.Color.white);
        no.setSelected(true);
        no.setText("Non");
        no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Compétences");

        skillToAddOrRemove.setMaximumRowCount(25);
        skillToAddOrRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillToAddOrRemoveActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Connexion");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        approveButton.setText("Ok");

        swapButton.setLabel("swapButton");

        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Mes compétences");

        chosenFileLabel.setForeground(new java.awt.Color(255, 255, 255));
        chosenFileLabel.setText("t");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(surname)
                                    .addComponent(login))
                                .addGap(82, 82, 82))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swapButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skillToAddOrRemove, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chosenSkills, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(approveButton)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(inscription, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chosenFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(infosInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {no, role, skillToAddOrRemove, yes});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jToggleButton1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yes))
                            .addComponent(password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(skillToAddOrRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(approveButton)
                                    .addComponent(swapButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chosenSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile)
                    .addComponent(chosenFileLabel))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inscription, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infosInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {firstname, jLabel1, jLabel10, jLabel11, jLabel12, jLabel2, jLabel3, jLabel4, jLabel5, jLabel8, jLabel9, login, no, password, profile, role, skillToAddOrRemove, surname, yes});

        approveButton.getAccessibleContext().setAccessibleName("approveButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscriptionActionPerformed

        UserModel.register(this);
        
    }//GEN-LAST:event_inscriptionActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
       
        javax.swing.JFileChooser myJFileChooser = new javax.swing.JFileChooser();
        int response = myJFileChooser.showOpenDialog(null);
        
        if (response == myJFileChooser.APPROVE_OPTION)
        {
            File file = new File(myJFileChooser.getSelectedFile().getAbsolutePath());
            String name = file.getName();
            myfile = file;
            // Un label est dédié à l'affichage du nom du fichier choisie
            chosenFileLabel.setText(name);
        }
    }//GEN-LAST:event_profileActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void skillToAddOrRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillToAddOrRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skillToAddOrRemoveActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.setVisible(false);
        this.parentTemp.setVisible(false);
        ConnexionPanel connect = new ConnexionPanel();
        connect.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    /**
     * This method grabs every name from the competence table of the database
     * @return an array of string
     */
    public ArrayList<String> LoadSkillList()
    {
        ServerCommunication s = new ServerCommunication();
        
        String res = s.sendGetRequest("retrieveAllCompetence=true");

        Object o = JSONValue.parse(res);
        JSONArray jsonArray = (JSONArray) o;         
        
        ArrayList<String> competences = new ArrayList<String>();
        
        try{
            
        
        for(Object object:jsonArray)
        {
            if(object instanceof JSONObject)
            {
                JSONObject jsonObject = (JSONObject)object;

                Set<String> keys =jsonObject.keySet();
                
                for(String key:keys)
                {
                   competences.add(key);
                }               
            }
        }
        }
        catch(NullPointerException e){
            competences.add("erreur de chargement");
            this.canCommunicateWithServer = false;
        }
        return competences;
    }
    
    public void swapAddVariable(){
         this.add = !this.add;
         swapButton.setText(swapButtonText(this.add));
     }
     /**
      * 
      * @param condition un pivot de décision
      * @return le text adéquat du bouton de swap
      */
     public String swapButtonText(boolean condition){
         String res;
         if (condition){
             res = "Ajouter";
         }
         else{res = "Supprimer";}
         return res;
     }
     
     public void addSkillToUser(){
         ServerCommunication s = new ServerCommunication();
         //s.sendPostRequest("competenceName=NomDeLaCompetence&login=LOGIN_USER" , );
     }

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup admin;
    private javax.swing.JButton approveButton;
    private javax.swing.JLabel chosenFileLabel;
    private javax.swing.JComboBox<String> chosenSkills;
    public javax.swing.JTextField firstname;
    public javax.swing.JLabel infosInscription;
    private javax.swing.JToggleButton inscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JTextField login;
    public javax.swing.JRadioButton no;
    public javax.swing.JTextArea others;
    public javax.swing.JPasswordField password;
    public javax.swing.JToggleButton profile;
    public javax.swing.JComboBox<String> role;
    private javax.swing.JComboBox<String> skillToAddOrRemove;
    public javax.swing.JTextField surname;
    private javax.swing.JButton swapButton;
    public javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
